In [36]:
import pandas as pd
import numpy as np

import sqlite3 as sql

con = sql.connect("eComDB.db")
cur = con.cursor()
cur.execute("SELECT * FROM userData")
rows = cur.fetchall()
df = pd.DataFrame(rows, columns=['transactionID', 'userID', 'ItemID'])
df

    transactionID  userID  ItemID
0             119       1     527
1             120       1    1042
2             121       1     833
3             122       1     688
4             123       1     995
5             124       1     592
6             125       1     648
7             126       1     832
8             127       1     493
9             128       1     543
10            129       1     733
11            130       1     872
12            131       1     814
13            132       1     825
14            133       1     695
15            134       1     857
16            135       1     644

In [66]:
cur.execute("SELECT id, title FROM items")
rows = cur.fetchall()
item = pd.DataFrame(rows, columns=['ItemID', 'foodTitle'])
item.shape

(641, 2)

In [95]:
df_merge = pd.merge(df, item, how='right')
df_merge['flag'] = 1
df_merge1 = df_merge[df_merge['userID']!=1.0]
df_merge2 = df_merge[df_merge['userID']==1.0]
#df_merge = df_merge.sort_values(by='ItemID', ascending=True)
df_merge1['flag'] = 0
df_merge = df_merge2.append(df_merge1)
df_merge['userID'] = 1.0
df_merge

C:\Users\pmuan\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,transactionID,userID,ItemID,foodTitle,flag
0,119.0,1.0,527,Mushroom Sauce Baked Pork Chops,1
1,120.0,1.0,1042,Pecan Chicken Breasts Stuffed with Cream Chees...,1
2,121.0,1.0,833,Potato Ham Bake,1
3,122.0,1.0,688,Bahamian Style Peas and Rice,1
4,123.0,1.0,995,Cranberry Apple Cider,1
5,124.0,1.0,592,Cheese and Bacon Potato Rounds,1
6,125.0,1.0,648,"Summer Pasta with Basil, Tomatoes and Cheese",1
7,126.0,1.0,832,Three-Cheese Potato Bake,1
8,127.0,1.0,493,Cinnamon Rolls III,1
9,128.0,1.0,543,Cranberry Gelatin Salad,1
10,129.0,1.0,733,Golden Au Gratin Potatoes,1
11,130.0,1.0,872,Almond Bars,1
12,131.0,1.0,814,White Bread II,1
13,132.0,1.0,825,Potato Ham Skillet,1
14,133.0,1.0,695,Shrimp and Catfish Gumbo,1
15,134.0,1.0,857,Sour Cream Sugar Cookies I,1
16,135.0,1.0,644,Bow-Tie Pasta With Red Pepper Sauce,1
17,NaN,1.0,471,Ginger Champagne,0
18,NaN,1.0,472,Potato and Cheese Frittata,0
19,NaN,1.0,473,Eggnog Thumbprints,0
20,NaN,1.0,474,Succulent Pork Roast,0
21,NaN,1.0,475,Irish Champ,0
22,NaN,1.0,476,Chocolate-Cherry Thumbprints,0
23,NaN,1.0,477,Mean Woman Pasta,0
24,NaN,1.0,478,Hot Spiced Cider,0
25,NaN,1.0,479,Isa's Cola de Mono,0
26,NaN,1.0,480,Amy's Barbecue Chicken Salad,0
27,NaN,1.0,481,Mushroom Pork Chops,0
28,NaN,1.0,482,Maryland Crab Cakes I,0
29,NaN,1.0,483,Black-Eyed Peas and Gumbo,0
...,...,...,...,...,...
611,NaN,1.0,1082,Red Beans and Rice Mix,0
612,NaN,1.0,1083,Fried Rice,0
613,NaN,1.0,1084,Italian Rice,0
614,NaN,1.0,1085,Cream of Sweet Potato Soup,0
615,NaN,1.0,1086,Spicy Sweet Potato and Coconut Soup,0
616,NaN,1.0,1087,Sweet Potato and Apple Soup,0
617,NaN,1.0,1088,Swanson&#174; Winter Vegetable Bean Soup with ...,0
618,NaN,1.0,1089,Easy Vegetable Soup,0
619,NaN,1.0,1090,Creamy Parsnip With Ginger Soup,0
620,NaN,1.0,1091,Creamy Potato With Rosemary Soup,0
621,NaN,1.0,1092,Creamy Carrot With Curry Soup,0
622,NaN,1.0,1093,Creamy Turnip With Paprika Soup,0
623,NaN,1.0,1094,Okra Gumbo,0
624,NaN,1.0,1095,Catfish Gumbo,0
625,NaN,1.0,1096,Seafood Gumbo,0
626,NaN,1.0,1097,Chicken Noodle Soup I,0
627,NaN,1.0,1098,Super Easy Chicken Noodle Soup,0
628,NaN,1.0,1099,Creamy Chicken and Wild Rice Soup,0
629,NaN,1.0,1100,Chicken Wild Rice Soup II,0
630,NaN,1.0,1101,Slow Cooker Chicken Creole,0
631,NaN,1.0,1102,Chicken Creole,0
632,NaN,1.0,1103,Texas Style Chicken Tequila,0
633,NaN,1.0,1104,Spring Rolls,0
634,NaN,1.0,1105,Vietnamese Fresh Spring Rolls,0
635,NaN,1.0,1106,Marinated Pork Strips,0
636,NaN,1.0,1107,Best Egg Rolls,0
637,NaN,1.0,1108,Oven Kalua Pork,0
638,NaN,1.0,1109,Slow Cooker Pork,0
639,NaN,1.0,1110,Quick and Easy Chicken Spaghetti,0
640,NaN,1.0,1111,Quick and Easy Chicken,0

In [96]:
userToFood = df_merge.pivot_table(index='userID',columns='foodTitle',values='flag')
userToFood.head(2)

foodTitle,A Pad Thai Worth Making,Almond Bars,Almond Fudge Topped Shortbread,Almond Raspberry Diamonds,Almond Shortbread Wafers,Amazingly Good Eggnog,American Frittata,Amish White Bread,Amy's Barbecue Chicken Salad,Angel Hair Pasta with Garlic Shrimp and Broccoli,...,White Chocolate-Macadamia Nut Oatmeal Cookies,Wild Asparagus Quiche,Wild Mushroom Puff Pastry,World's Best Oatmeal Cookies,Yakisoba Chicken,Yummy Pork Chops,Yummy Yellow Taters,Zesty Chicken and Potatoes,Zesty Pasta with Sausage,Zucchini Frittata
userID,,,,,,,,,,,,,,,,,,,,,
1.0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [97]:
matrix_corr = userToFood.corr(method='pearson',min_periods=100)
matrix_corr.head()

foodTitle,A Pad Thai Worth Making,Almond Bars,Almond Fudge Topped Shortbread,Almond Raspberry Diamonds,Almond Shortbread Wafers,Amazingly Good Eggnog,American Frittata,Amish White Bread,Amy's Barbecue Chicken Salad,Angel Hair Pasta with Garlic Shrimp and Broccoli,...,White Chocolate-Macadamia Nut Oatmeal Cookies,Wild Asparagus Quiche,Wild Mushroom Puff Pastry,World's Best Oatmeal Cookies,Yakisoba Chicken,Yummy Pork Chops,Yummy Yellow Taters,Zesty Chicken and Potatoes,Zesty Pasta with Sausage,Zucchini Frittata
foodTitle,,,,,,,,,,,,,,,,,,,,,
A Pad Thai Worth Making,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Almond Bars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Almond Fudge Topped Shortbread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Almond Raspberry Diamonds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Almond Shortbread Wafers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN