In [36]:
import pandas as pd
import numpy as np

import sqlite3 as sql

con = sql.connect("eComDB.db")
cur = con.cursor()
cur.execute("SELECT * FROM userData")
rows = cur.fetchall()
df = pd.DataFrame(rows, columns=['transactionID', 'userID', 'ItemID'])
df

    transactionID  userID  ItemID
0             119       1     527
1             120       1    1042
2             121       1     833
3             122       1     688
4             123       1     995
5             124       1     592
6             125       1     648
7             126       1     832
8             127       1     493
9             128       1     543
10            129       1     733
11            130       1     872
12            131       1     814
13            132       1     825
14            133       1     695
15            134       1     857
16            135       1     644

In [66]:
cur.execute("SELECT id, title FROM items")
rows = cur.fetchall()
item = pd.DataFrame(rows, columns=['ItemID', 'foodTitle'])
item.shape

(641, 2)

In [72]:
df_merge = pd.merge(df, item, how='right')
df_merge['flag'] = 1
df_merge1 = df_merge.iloc[df_merge['userID']!=1]
df_merge2 = df_merge.iloc[df_merge['userID']==1]
df_merge1.iloc['flag'] = 0
df_merge2 = df_merge1.append(df_merge2)
#df_merge = df_merge.sort_values(by='ItemID', ascending=True)
df_merge

C:\Users\pmuan\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

,transactionID,userID,ItemID,foodTitle,flag
0,119.0,1.0,527,Mushroom Sauce Baked Pork Chops,1
1,120.0,1.0,1042,Pecan Chicken Breasts Stuffed with Cream Chees...,1
2,121.0,1.0,833,Potato Ham Bake,1
3,122.0,1.0,688,Bahamian Style Peas and Rice,1
4,123.0,1.0,995,Cranberry Apple Cider,1
5,124.0,1.0,592,Cheese and Bacon Potato Rounds,1
6,125.0,1.0,648,"Summer Pasta with Basil, Tomatoes and Cheese",1
7,126.0,1.0,832,Three-Cheese Potato Bake,1
8,127.0,1.0,493,Cinnamon Rolls III,1
9,128.0,1.0,543,Cranberry Gelatin Salad,1
10,129.0,1.0,733,Golden Au Gratin Potatoes,1
11,130.0,1.0,872,Almond Bars,1
12,131.0,1.0,814,White Bread II,1
13,132.0,1.0,825,Potato Ham Skillet,1
14,133.0,1.0,695,Shrimp and Catfish Gumbo,1
15,134.0,1.0,857,Sour Cream Sugar Cookies I,1
16,135.0,1.0,644,Bow-Tie Pasta With Red Pepper Sauce,1
17,NaN,NaN,471,Ginger Champagne,1
18,NaN,NaN,472,Potato and Cheese Frittata,1
19,NaN,NaN,473,Eggnog Thumbprints,1
20,NaN,NaN,474,Succulent Pork Roast,1
21,NaN,NaN,475,Irish Champ,1
22,NaN,NaN,476,Chocolate-Cherry Thumbprints,1
23,NaN,NaN,477,Mean Woman Pasta,1
24,NaN,NaN,478,Hot Spiced Cider,1
25,NaN,NaN,479,Isa's Cola de Mono,1
26,NaN,NaN,480,Amy's Barbecue Chicken Salad,1
27,NaN,NaN,481,Mushroom Pork Chops,1
28,NaN,NaN,482,Maryland Crab Cakes I,1
29,NaN,NaN,483,Black-Eyed Peas and Gumbo,1
...,...,...,...,...,...
611,NaN,NaN,1082,Red Beans and Rice Mix,1
612,NaN,NaN,1083,Fried Rice,1
613,NaN,NaN,1084,Italian Rice,1
614,NaN,NaN,1085,Cream of Sweet Potato Soup,1
615,NaN,NaN,1086,Spicy Sweet Potato and Coconut Soup,1
616,NaN,NaN,1087,Sweet Potato and Apple Soup,1
617,NaN,NaN,1088,Swanson&#174; Winter Vegetable Bean Soup with ...,1
618,NaN,NaN,1089,Easy Vegetable Soup,1
619,NaN,NaN,1090,Creamy Parsnip With Ginger Soup,1
620,NaN,NaN,1091,Creamy Potato With Rosemary Soup,1
621,NaN,NaN,1092,Creamy Carrot With Curry Soup,1
622,NaN,NaN,1093,Creamy Turnip With Paprika Soup,1
623,NaN,NaN,1094,Okra Gumbo,1
624,NaN,NaN,1095,Catfish Gumbo,1
625,NaN,NaN,1096,Seafood Gumbo,1
626,NaN,NaN,1097,Chicken Noodle Soup I,1
627,NaN,NaN,1098,Super Easy Chicken Noodle Soup,1
628,NaN,NaN,1099,Creamy Chicken and Wild Rice Soup,1
629,NaN,NaN,1100,Chicken Wild Rice Soup II,1
630,NaN,NaN,1101,Slow Cooker Chicken Creole,1
631,NaN,NaN,1102,Chicken Creole,1
632,NaN,NaN,1103,Texas Style Chicken Tequila,1
633,NaN,NaN,1104,Spring Rolls,1
634,NaN,NaN,1105,Vietnamese Fresh Spring Rolls,1
635,NaN,NaN,1106,Marinated Pork Strips,1
636,NaN,NaN,1107,Best Egg Rolls,1
637,NaN,NaN,1108,Oven Kalua Pork,1
638,NaN,NaN,1109,Slow Cooker Pork,1
639,NaN,NaN,1110,Quick and Easy Chicken Spaghetti,1
640,NaN,NaN,1111,Quick and Easy Chicken,1

In [44]:
userToFood = df_merge.pivot_table(index='userID',columns='foodTitle',values='flag')
userToFood.head(2)

foodTitle,Almond Bars,Bahamian Style Peas and Rice,Bow-Tie Pasta With Red Pepper Sauce,Cheese and Bacon Potato Rounds,Cinnamon Rolls III,Cranberry Apple Cider,Cranberry Gelatin Salad,Golden Au Gratin Potatoes,Mushroom Sauce Baked Pork Chops,Pecan Chicken Breasts Stuffed with Cream Cheese and Broccoli,Potato Ham Bake,Potato Ham Skillet,Shrimp and Catfish Gumbo,Sour Cream Sugar Cookies I,"Summer Pasta with Basil, Tomatoes and Cheese",Three-Cheese Potato Bake,White Bread II
userID,,,,,,,,,,,,,,,,,
1.0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [14]:
matrix_corr = userToFood.corr(method='pearson',min_periods=100)
matrix_corr.head()

foodTitle,Almond Bars,Bahamian Style Peas and Rice,Bow-Tie Pasta With Red Pepper Sauce,Cheese and Bacon Potato Rounds,Cinnamon Rolls III,Cranberry Apple Cider,Cranberry Gelatin Salad,Golden Au Gratin Potatoes,Mushroom Sauce Baked Pork Chops,Pecan Chicken Breasts Stuffed with Cream Cheese and Broccoli,Potato Ham Bake,Potato Ham Skillet,Shrimp and Catfish Gumbo,Sour Cream Sugar Cookies I,"Summer Pasta with Basil, Tomatoes and Cheese",Three-Cheese Potato Bake,White Bread II
foodTitle,,,,,,,,,,,,,,,,,
Almond Bars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bahamian Style Peas and Rice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bow-Tie Pasta With Red Pepper Sauce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cheese and Bacon Potato Rounds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cinnamon Rolls III,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN